'''
Created on Jul 8, 2011

@author: kevin
'''

# REQUEST RELATED
INVALID_ARGUMENTS = 1001
# PURCHASE RELATED
NOT_ENOUGH_AVAILABLE_TICKETS = 2001
ORDER_ALREADY_CONFIRMED      = 2002
ORDER_DOES_NOT_EXIST         = 2003